ports:
  - port: 3000
    visibility: public

  - port: 8000
    visibility: public

  - port: 5000-5999
    visibility: private
    onOpen: ignore

tasks:
  - init: npm install
    command: nginx

  - name: Accounts Service
    before: cd accounts-service
    init: npm install
    command: |
      export CLIENT_URL=$(gp url 3000)
      export GOOGLE_OAUTH_CALLBACK_URL=$(gp url 8000)/accounts-service/auth/google/callback
      npm run dev

  - name: Messages Service
    before: cd messages-service
    init: npm install
    command: |
      export CLIENT_URL=$(gp url 3000)
      npm run dev

  - name: Client
    before: cd client
    init: npm install
    command: |
      export REACT_APP_CLIENT_URL=$(gp url 3000)
      export REACT_APP_SERVER_URL=$(gp url 8000)
      npm start

  - name: Infra
    before: cd infra
    init: |
      eval $(command gp env -e)
      terraform init
    
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - hashicorp.terraform
    - esbenp.prettier-vscode
    - bradlc.vscode-tailwindcss