tasks:
  - init: npm install
    command: |
      export REACT_APP_CLIENT_URL=$(gp url 3000)
      export REACT_APP_SERVER_URL=$(gp url 8000)
      export CLIENT_URL=$REACT_APP_CLIENT_URL
      export GOOGLE_OAUTH_CALLBACK_URL=$REACT_APP_SERVER_URL/accounts-service/auth/google/callback

  - name: Accounts Service
    before: cd accounts-service
    init: npm install
    command: npm run dev

  - name: Messages Service
    before: cd messages-service
    init: npm install
    command: npm run dev

  - name: Client
    before: cd client
    init: npm install
    command: npm start

  - name: Common
    before: cd common
    init: npm install
