version: '3.8'

services:
  mongodb:
    image: bitnami/mongodb
    container_name: mongodb-dev
    restart: always
    ports:
      - 27017:27017
    environment:
      ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - ./data/mongodb:/bitnami/mongodb
  postgresql:
    image: bitnami/postgresql
    container_name: postgresql-dev
    restart: always
    ports:
      - 5432:5432
    environment:
      ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - ./data/postgresql:/bitnami/postgresql
  zookeeper:
    image: bitnami/zookeeper
    container_name: zookeeper-dev
    restart: always
    ports:
      - 2181:2181
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'true'
    volumes:
      - ./data/zookeeper:/bitnami/zookeeper
  kafka:
    image: bitnami/kafka
    container_name: kafka-dev
    restart: always
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: 'true'
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: CLIENT://:9092,EXTERNAL://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: CLIENT
    volumes:
      - ./data/kafka:/bitnami/kafka
