apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: abhithube/chatterbox-auth
          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '256Mi'
              cpu: '200m'
          env:
            - name: PORT
              value: '80'
            - name: CLIENT_URL
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: CLIENT_URL
            - name: SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: SERVER_URL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: DATABASE_URL
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: REDIS_PASSWORD
            - name: BROKER_URLS
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: BROKER_URLS
            - name: CONFLUENT_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: CONFLUENT_API_KEY
            - name: CONFLUENT_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: CONFLUENT_API_SECRET
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: GOOGLE_CLIENT_SECRET
            - name: GITHUB_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: GITHUB_CLIENT_ID
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: GITHUB_CLIENT_SECRET
            - name: SMTP_HOST
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: SMTP_HOST
            - name: SMTP_USER
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: SMTP_USER
            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: SMTP_PASS
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: JWT_SECRET
            - name: EMAIL_NAME
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: EMAIL_NAME
            - name: EMAIL_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: EMAIL_ADDRESS
