apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  GOOGLE_CLIENT_ID: 445749772447-b7jo4spg4up3hpd946i0jsmjvksf8glg.apps.googleusercontent.com
  GITHUB_CLIENT_ID: 7cec12176d6f90068478
