apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact
  template:
    metadata:
      labels:
        app: contact
    spec:
      containers:
        - name: contact
          image: abhithube/chatterbox-contact
          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '256Mi'
              cpu: '200m'
          env:
            - name: PORT
              value: '80'
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: NODE_ENV
            - name: CLIENT_URL
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: CLIENT_URL
            - name: BROKER_URLS
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: BROKER_URLS
            - name: KAFKA_USER
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: KAFKA_USER
            - name: KAFKA_PASS
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: KAFKA_PASS
            - name: MAIL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: contact-secrets
                  key: MAIL_API_KEY
            - name: EMAIL_NAME
              valueFrom:
                configMapKeyRef:
                  name: contact-config
                  key: EMAIL_NAME
            - name: EMAIL_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: contact-config
                  key: EMAIL_ADDRESS
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: contact-svc
spec:
  type: ClusterIP
  selector:
    app: contact
  ports:
    - name: contact
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: contact-config
data:
  SMTP_HOST: smtp.sendgrid.net
  SMTP_USER: apikey
  EMAIL_NAME: Chatterbox
  EMAIL_ADDRESS: chatterbox@abhithube.com
