apiVersion: apps/v1
kind: Deployment
metadata:
  name: messages-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messages
  template:
    metadata:
      labels:
        app: messages
    spec:
      containers:
        - name: messages
          image: abhithube/chatterbox-messages
          resources:
            requests:
              memory: '256Mi'
              cpu: '500m'
            limits:
              memory: '512Mi'
              cpu: '1'
          env:
            - name: PORT
              value: '80'
            - name: CLIENT_URL
              value: http://localhost:3000
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: MESSAGES_DATABASE_URL
            - name: REDIS_HOST
              value: usw1-enabling-quail-31250.upstash.io
            - name: REDIS_PORT
              value: '31250'
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: MESSAGES_REDIS_PASSWORD
            - name: BROKER_URLS
              value: pkc-pgq85.us-west-2.aws.confluent.cloud:9092
            - name: CONFLUENT_API_KEY
              value: Q7SVQ7P55SXWGETA
            - name: CONFLUENT_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: kafka
                  key: CONFLUENT_API_SECRET
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: messages-srv
spec:
  type: ClusterIP
  selector:
    app: messages
  ports:
    - name: messages
      protocol: TCP
      port: 80
      targetPort: 80
