apiVersion: v1
kind: Service
metadata:
  name: messages-svc
spec:
  type: ClusterIP
  selector:
    app: messages
  ports:
    - name: messages
      protocol: TCP
      port: 80
      targetPort: 80
