apiVersion: apps/v1
kind: Deployment
metadata:
  name: profiles-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profiles
  template:
    metadata:
      labels:
        app: profiles
    spec:
      containers:
        - name: profiles
          image: abhithube/chatterbox-profiles
          resources:
            requests:
              memory: '256Mi'
              cpu: '500m'
            limits:
              memory: '512Mi'
              cpu: '1'
          env:
            - name: PORT
              value: '80'
            - name: CLIENT_URL
              value: http://localhost:3000
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: PROFILES_DATABASE_URL
            - name: BROKER_URLS
              value: pkc-pgq85.us-west-2.aws.confluent.cloud:9092
            - name: CONFLUENT_API_KEY
              value: Q7SVQ7P55SXWGETA
            - name: CONFLUENT_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: kafka
                  key: CONFLUENT_API_SECRET
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: profiles-srv
spec:
  type: ClusterIP
  selector:
    app: profiles
  ports:
    - name: profiles
      protocol: TCP
      port: 80
      targetPort: 80
