/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "ChatterboxNext": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "DynamoTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "SnsTopic": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}