version: '3.8'

services:
  db:
    image: bitnami/postgresql
    container_name: postgres-dev
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: parties-service
    volumes:
      - ./data/postgres:/bitnami/postgresql
