name: Parties Service CI

on:
  push:
    branches: [main]
    paths:
      - 'parties-service/**'
  pull_request:
    branches: [main]
    paths:
      - 'parties-service/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          ALLOW_EMPTY_PASSWORD: 'true'
        options: >-
          --health-cmd "pg_isready --username=postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm ci
      - name: Build source code
        run: npm run build
      - name: Run unit tests
        run: npm test
      - name: Run integration tests
        run: npm run test:int
        env:
          DATABASE_URL: postgresql://postgres@localhost:5432/test

defaults:
  run:
    working-directory: parties-service
