name: Users Service CI

on:
  push:
    branches: [main]
    paths:
      - 'users-service/**'
  pull_request:
    branches: [main]
    paths:
      - 'users-service/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: bitnami/mongodb
        ports:
          - 27017:27017
        env:
          ALLOW_EMPTY_PASSWORD: 'true'
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      zookeeper:
        image: bitnami/zookeeper
        ports:
          - 2181:2181
        env:
          ALLOW_ANONYMOUS_LOGIN: 'true'
      kafka:
        image: bitnami/kafka
        ports:
          - 9093:9093
        env:
          KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
          ALLOW_PLAINTEXT_LISTENER: 'true'
          KAFKA_CFG_LISTENERS: PLAINTEXT://:9093
          KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm ci
      - name: Build source code
        run: npm run build
      - name: Run unit tests
        run: npm test
      - name: Run integration tests
        run: npm run test:int
        env:
          DATABASE_URL: mongodb://localhost:27017/test
          KAFKA_TOPIC_USERS: test

defaults:
  run:
    working-directory: users-service
