name: Users Service CI

on:
  push:
    branches: [main]
    paths:
      - 'users-service/**'
  pull_request:
    branches: [main]
    paths:
      - 'users-service/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: bitnami/mongodb
        ports:
          - 27017:27017
        env:
          MONGODB_USERNAME: mongo
          MONGODB_PASSWORD: mongo
          MONGODB_DATABASE: test

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm ci
      - name: Build source code
        run: npm run build
      - name: Run tests
        run: npm test
        env:
          DATABASE_URL: mongodb://mongo:mongo@localhost:27017/test

defaults:
  run:
    working-directory: users-service
